---
name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Docker Tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            DOCKER_TAG="${GITHUB_REF:10}"
          elif [[ $GITHUB_REF == refs/heads/master ]]; then
            DOCKER_TAG="latest"
          elif [[ $GITHUB_REF == refs/heads/dev ]]; then
            DOCKER_TAG="dev"
          else
            DOCKER_TAG="${GITHUB_REF:11}"
          fi
          echo ::set-output name=tag::${DOCKER_TAG}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/')
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le
          tags: ${{ secrets.DOCKER_USERNAME }}/vanillavotifier:${{ steps.tag.outputs.tag }}
